name: architecture_template_v1
description: "Flutter project architecture template."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #App
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  # flutter_native_splash: ^2.3.6 -> dart run flutter_native_splash:create


  #Utility
  grock: ^0.5.5
  google_fonts: ^6.1.0


  #State Management
  flutter_riverpod: ^2.4.9

  #Network
  dio: ^5.4.0

  #Navigation
  go_router: ^12.1.1

  #Config
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.0
  intl: ^0.18.1

  #UI
  cupertino_icons: ^1.0.6
  flutter_easyloading: ^3.0.5
  # lottie: ^2.7.0
  # flutter_svg: ^2.0.9
  # cached_network_image: ^3.3.0

  #Database
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # flutter pub run flutter_launcher_icons
  build_runner: ^2.4.7 # flutter pub run build_runner build --delete-conflicting-outputs # -> dart run build_runner build
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  # change_app_package_name: ^1.1.0 -> flutter pub run change_app_package_name:main com.new.package.name

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/im_splash.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  android_12:
    image: assets/image/im_splash.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icon/
    - assets/image/
    - assets/font/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
